# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_overlap": "00_cifar.ipynb",
         "CifarFactory": "00_cifar.ipynb"}

modules = ["cifar_utils.py"]

doc_url = "https://puhsu.github.io/sssupervised/"

git_url = "https://github.com/puhsu/sssupervised/tree/master/"

def custom_doc_links(name): return None
